/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-surface": "#1a1c1a",
        "surface-dim": "#dbdad7",
        "on-primary-fixed": "#120364",
        "primary": "#1a106b",
        "on-background": "#1a1c1a",
        "surface-container-lowest": "#ffffff",
        "secondary": "#4e6700",
        "surface-tint": "#5854a9",
        "surface-container-highest": "#e3e2df",
        "secondary-fixed-dim": "#b1d35a",
        "tertiary-container": "#2d3d00",
        "inverse-on-surface": "#f2f1ee",
        "inverse-surface": "#2f312f",
        "inverse-primary": "#c4c0ff",
        "surface-container-low": "#f4f3f0",
        "surface-container": "#efeeeb",
        "on-primary-fixed-variant": "#403b90",
        "tertiary-fixed-dim": "#b1d35a",
        "on-tertiary": "#ffffff",
        "primary-container": "#312b80",
        "on-surface-variant": "#474551",
        "on-error-container": "#93000a",
        "on-primary-container": "#9c97f2",
        "surface-variant": "#e3e2df",
        "on-tertiary-fixed": "#151f00",
        "outline-variant": "#c8c5d3",
        "secondary-container": "#ccf073",
        "on-secondary-container": "#536d00",
        "surface-bright": "#faf9f6",
        "error": "#ba1a1a",
        "background": "#faf9f6",
        "surface-container-high": "#e9e8e5",
        "tertiary-fixed": "#ccf073",
        "outline": "#787582",
        "surface": "#faf9f6",
        "on-tertiary-container": "#8cac38",
        "on-secondary-fixed": "#151f00",
        "primary-fixed-dim": "#c4c0ff",
        "tertiary": "#1b2600",
        "error-container": "#ffdad6",
        "primary-fixed": "#e3dfff",
        "secondary-fixed": "#ccf073",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Playfair Display", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "sans": ["Manrope", "sans-serif"],
        "serif": ["Playfair Display", "serif"],
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      boxShadow: {
        "primary": "0px 20px 40px rgba(49, 43, 128, 0.06)",
        "primary-lg": "0px 20px 40px rgba(49, 43, 128, 0.15)",
      },
      animation: {
        "fade-in": "fadeIn 0.6s ease-out forwards",
        "slide-up": "slideUp 0.6s ease-out forwards",
        "slide-in-left": "slideInLeft 0.6s ease-out forwards",
        "marquee": "marquee 35s linear infinite",
        "slide-down": "slideDown 0.5s ease-out forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-100%)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
}
